services:
  api:
    build: .
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    volumes:
      - ./.env:/app/.env
      - ./app:/app/app
    depends_on:
      - mongodb
    networks:
      - crypto_network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - crypto_network
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local

networks:
  crypto_network:
    driver: bridge